apiVersion: 1

datasources:
  - name: Veto Live Prometheus
    uid: veto-live-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
