import json
import streamlit as st
import pandas as pd
from pathlib import Path
from datetime import datetime

# ====================== CONFIG ======================
DEFAULT_CACHE_FOLDER = Path(r"D:\Veto Logs Backup\veto Stream logs\dashboard_cache")

CARD_COLOURS = [
    "#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4", "#FFEAA7",
    "#DDA0DD", "#98D8C8", "#F7C6C6", "#B5D4F4", "#C0DD97",
    "#FFB347", "#87CEEB", "#DEB887", "#90EE90", "#FFB6C1",
]


# ====================== CACHE LOADER ======================
@st.cache_data(ttl=300)   # re-reads from disk at most every 5 minutes
def load_cache(cache_folder: str):
    """
    Reads the three pre-generated parquet files + meta.json.
    Returns (channel_df, user_df, unmapped_df, meta) or raises on missing files.
    """
    p = Path(cache_folder)
    required = ["channel_summary.parquet", "top_users.parquet",
                "unmapped_ids.parquet", "meta.json"]
    missing = [f for f in required if not (p / f).exists()]
    if missing:
        raise FileNotFoundError(
            f"Missing cache files in {p}:\n  " + "\n  ".join(missing) +
            "\n\nRun  generate_cache.py  first to build the cache."
        )

    channel_df  = pd.read_parquet(p / "channel_summary.parquet")
    user_df     = pd.read_parquet(p / "top_users.parquet")
    unmapped_df = pd.read_parquet(p / "unmapped_ids.parquet")
    meta        = json.loads((p / "meta.json").read_text())
    return channel_df, user_df, unmapped_df, meta


# ====================== PAGE SETUP ======================
st.set_page_config(page_title="Live TV Dashboard", layout="wide")
st.title("📺 Live TV Channel Watch Dashboard")
st.markdown("---")


# ====================== SIDEBAR ======================
with st.sidebar:
    st.header("⚙️ Settings")

    cache_input = st.text_input(
        "Cache Folder Path",
        value=str(DEFAULT_CACHE_FOLDER),
        help="Folder that contains channel_summary.parquet, top_users.parquet, "
             "unmapped_ids.parquet and meta.json — generated by generate_cache.py"
    )

    st.markdown("---")
    st.markdown(
        "**How to refresh data:**\n"
        "Run `generate_cache.py` on the server, then click **Reload Cache** below."
    )
    reload_btn = st.button("🔄 Reload Cache", type="primary", use_container_width=True)
    if reload_btn:
        st.cache_data.clear()

    show_debug = st.checkbox("🔎 Show unmapped channel IDs", value=False)


# ====================== LOAD ======================
try:
    channel_df, user_df, unmapped_df, meta = load_cache(cache_input)
except FileNotFoundError as e:
    st.error(str(e))
    st.stop()
except Exception as e:
    st.error(f"Failed to load cache: {e}")
    st.stop()


# ====================== META BANNER ======================
generated_at = meta.get("generated_at", "unknown")
try:
    generated_at = datetime.fromisoformat(generated_at).strftime("%d %b %Y, %I:%M %p")
except Exception:
    pass

start_str = meta.get("start_date", "?")
end_str   = meta.get("end_date",   "?")

st.markdown(
    f"**Data period:** {start_str} → {end_str} &nbsp;&nbsp;|&nbsp;&nbsp; "
    f"**Cache generated:** {generated_at}"
)


# ====================== KPI ROW ======================
c1, c2, c3, c4 = st.columns(4)
with c1: st.metric("Total Channels",    meta.get("total_channels",       len(channel_df[channel_df["channel_name"] != "Other"])))
with c2: st.metric("Total Watch Hours", f"{meta.get('total_watch_hours', channel_df['watch_hours'].sum()):,.0f}")
with c3: st.metric("Unique Viewers",    f"{meta.get('total_unique_viewers', channel_df['unique_viewers'].sum()):,}")
with c4: st.metric("Total Chunks",      f"{meta.get('total_chunks', channel_df['total_chunks'].sum()):,}")

st.markdown("---")


# ====================== CHANNEL CARDS ======================
st.subheader("📡 Channel Performance")

display_df = channel_df[channel_df["channel_name"] != "Other"].reset_index(drop=True)
other_row  = channel_df[channel_df["channel_name"] == "Other"]

cols = st.columns(3)
for idx, row in display_df.iterrows():
    colour = CARD_COLOURS[idx % len(CARD_COLOURS)]
    with cols[idx % 3]:
        st.markdown(f"""
        <div style="background-color:{colour}; padding:1.2rem; border-radius:15px;
                    margin-bottom:1rem; color:black;">
            <h3 style="margin:0 0 .4rem">{row['channel_name']}</h3>
            <p style="margin:.2rem 0"><b>{row['watch_hours']:.1f}</b> hrs watched</p>
            <p style="margin:.2rem 0">👥 {row['unique_viewers']:,} viewers</p>
            <p style="margin:.2rem 0">🎬 {row['total_chunks']:,} chunks</p>
            <p style="margin:.2rem 0">Avg: {row['avg_watch_hours_per_viewer']:.2f} hrs/viewer</p>
        </div>
        """, unsafe_allow_html=True)

# Other / unmapped bar
if not other_row.empty:
    r = other_row.iloc[0]
    st.markdown(f"""
    <div style="background-color:#d3d3d3; padding:1rem; border-radius:12px;
                margin-bottom:1rem; color:#333;">
        <b>Other / Unmapped</b> — {r['watch_hours']:.1f} hrs &nbsp;|&nbsp;
        👥 {r['unique_viewers']:,} viewers &nbsp;|&nbsp;
        🎬 {r['total_chunks']:,} chunks
    </div>
    """, unsafe_allow_html=True)

    if show_debug:
        with st.expander("🔎 Unmapped raw channel IDs (add these to CHANNEL_MAP)"):
            if unmapped_df.empty:
                st.success("No unmapped IDs — everything is resolved!")
            else:
                st.dataframe(
                    unmapped_df[["channel_id", "unique_viewers",
                                 "total_chunks", "watch_hours"]].style.format({
                        "watch_hours":    "{:.2f} hrs",
                        "total_chunks":   "{:,}",
                        "unique_viewers": "{:,}",
                    }),
                    use_container_width=True,
                    hide_index=True,
                )

st.markdown("---")


# ====================== TOP VIEWERS ======================
st.subheader("🏆 Top Viewers by Channel")

all_channels = channel_df["channel_name"].tolist()
selected_channel = st.selectbox("Select Channel", all_channels)

if selected_channel:
    top_users = user_df[user_df["channel_name"] == selected_channel].head(15)
    if not top_users.empty:
        st.dataframe(
            top_users[["cliIP", "watch_hours", "chunks_watched"]].style.format({
                "watch_hours":    "{:.2f} hrs",
                "chunks_watched": "{:,}",
            }),
            use_container_width=True,
            hide_index=True,
        )
    else:
        st.info("No viewer data for this channel in the current cache.")


# ====================== DOWNLOADS ======================
col_dl1, col_dl2 = st.columns(2)
with col_dl1:
    st.download_button(
        "📥 Channel Report",
        channel_df.to_csv(index=False).encode("utf-8"),
        "channel_report.csv", "text/csv"
    )
with col_dl2:
    st.download_button(
        "📥 User Report",
        user_df.to_csv(index=False).encode("utf-8"),
        "user_report.csv", "text/csv"
    )
