from __future__ import annotations

import time
from pathlib import Path
from typing import Optional

from playwright.sync_api import (
    BrowserContext,
    Error as PlaywrightError,
    Locator,
    Page,
    TimeoutError as PlaywrightTimeoutError,
    sync_playwright,
)

PORTAL_URL = "https://indiatvfast.now3.amagi.tv/partner/analytics/concurrency"
PROFILE_FOLDER = Path("amagi_browser_profile").resolve()
DOWNLOAD_FOLDER = Path("downloads").resolve()

# ============================================================
# FIRST RUN: keep this True to open Playwright Inspector.
# AFTER COPYING THE EXACT LOCATORS BELOW: change it to False.
# ============================================================
MAP_MODE = True


# ============================================================
# PASTE THE LOCATORS GENERATED BY "PICK LOCATOR" BELOW.
#
# Example generated locator:
#     page.get_by_role("button", name="Yesterday")
#
# Replace only the return line inside each function.
# ============================================================

def yesterday_locator(page: Page) -> Locator:
    # Replace this return line with the exact locator copied from Inspector.
    return page.get_by_text("Yesterday", exact=True)


def download_locator(page: Page) -> Locator:
    # Replace this return line with the exact locator copied from Inspector.
    # The temporary fallback below may not match an icon-only button.
    return page.get_by_role("button", name="Download")


def download_format_locator(page: Page) -> Optional[Locator]:
    """
    If clicking Download opens a CSV/Excel/XLSX menu, replace `return None`
    with the exact locator for the required menu item.

    Example:
        return page.get_by_role("menuitem", name="CSV")

    If the Download button starts the file directly, leave this as None.
    """
    return None


def optional_apply_locator(page: Page) -> Optional[Locator]:
    """
    If selecting Yesterday opens a date picker that requires Apply/Confirm,
    replace `return None` with that button's exact locator.
    """
    return None


def launch_browser(playwright) -> BrowserContext:
    options = {
        "user_data_dir": str(PROFILE_FOLDER),
        "headless": False,
        "viewport": {"width": 1440, "height": 900},
        "accept_downloads": True,
    }

    try:
        return playwright.chromium.launch_persistent_context(
            channel="msedge",
            **options,
        )
    except PlaywrightError as edge_error:
        print(f"Microsoft Edge could not be started: {edge_error}")
        print("Trying Playwright Chromium...")

        return playwright.chromium.launch_persistent_context(**options)


def open_dashboard(page: Page) -> None:
    try:
        page.goto(
            PORTAL_URL,
            wait_until="domcontentloaded",
            timeout=60000,
        )
    except PlaywrightTimeoutError:
        print("The page is taking longer to load, but the browser is open.")

    page.wait_for_timeout(3000)

    if "login.amagi.tv" in page.url.lower():
        print()
        print("The saved login has expired.")
        print("Log in manually in the browser.")
        input(
            "After the Concurrency dashboard is visible, "
            "return here and press Enter... "
        )

        page.goto(
            PORTAL_URL,
            wait_until="domcontentloaded",
            timeout=60000,
        )
        page.wait_for_timeout(3000)


def run_mapping_mode(page: Page) -> None:
    print()
    print("=" * 65)
    print("MANUAL LOCATOR MAPPING")
    print("=" * 65)
    print("1. In Playwright Inspector, click 'Pick Locator'.")
    print("2. Click the visible 'Yesterday' control in the browser.")
    print("3. Click 'Copy Locator' and paste it into yesterday_locator().")
    print("4. Pick and copy the Download/Export icon or button.")
    print("5. Paste it into download_locator().")
    print("6. If a CSV/Excel menu appears, map that option too.")
    print("7. Save this file and change MAP_MODE to False.")
    print()
    print("The script is now paused. Use the Inspector window.")

    # This opens Playwright Inspector in headed mode.
    page.pause()

    input("Press Enter to close the browser after copying the locators... ")


def wait_for_download(
    page: Page,
    downloads: list,
    timeout_seconds: int,
):
    deadline = time.monotonic() + timeout_seconds

    while time.monotonic() < deadline:
        if downloads:
            return downloads[0]
        page.wait_for_timeout(500)

    return None


def run_download_mode(page: Page) -> Path:
    print('Clicking the mapped "Yesterday" control...')
    yesterday = yesterday_locator(page)
    yesterday.wait_for(state="visible", timeout=30000)
    yesterday.scroll_into_view_if_needed()
    yesterday.click(timeout=30000)

    apply_button = optional_apply_locator(page)
    if apply_button is not None:
        apply_button.wait_for(state="visible", timeout=15000)
        apply_button.click(timeout=15000)
        print("Clicked the mapped Apply/Confirm control.")

    # Allow charts/API results to refresh.
    page.wait_for_timeout(8000)

    downloads = []
    page.on("download", lambda item: downloads.append(item))

    print("Clicking the mapped Download/Export control...")
    download_button = download_locator(page)
    download_button.wait_for(state="visible", timeout=30000)
    download_button.scroll_into_view_if_needed()
    download_button.click(timeout=30000)

    # Some dashboards download immediately; others open a format menu.
    download = wait_for_download(page, downloads, timeout_seconds=5)

    if download is None:
        format_option = download_format_locator(page)

        if format_option is None:
            page.screenshot(
                path="download_menu_needs_mapping.png",
                full_page=True,
            )
            raise RuntimeError(
                "The Download control did not start a direct download. "
                "It probably opened a CSV/Excel menu. Map that menu option "
                "inside download_format_locator(). A screenshot was saved as "
                "download_menu_needs_mapping.png."
            )

        print("Clicking the mapped CSV/Excel/XLSX menu option...")
        format_option.wait_for(state="visible", timeout=15000)
        format_option.scroll_into_view_if_needed()
        format_option.click(timeout=15000)

        download = wait_for_download(
            page,
            downloads,
            timeout_seconds=90,
        )

    if download is None:
        page.screenshot(
            path="download_did_not_start.png",
            full_page=True,
        )
        raise RuntimeError(
            "No browser download event was detected. "
            "A screenshot was saved as download_did_not_start.png."
        )

    safe_name = Path(download.suggested_filename).name
    output_path = DOWNLOAD_FOLDER / safe_name
    download.save_as(str(output_path))

    page.screenshot(
        path="amagi_after_success.png",
        full_page=True,
    )

    return output_path


def main() -> int:
    PROFILE_FOLDER.mkdir(parents=True, exist_ok=True)
    DOWNLOAD_FOLDER.mkdir(parents=True, exist_ok=True)

    with sync_playwright() as playwright:
        browser = launch_browser(playwright)
        page = browser.pages[0] if browser.pages else browser.new_page()
        page.set_default_timeout(30000)

        try:
            open_dashboard(page)

            if MAP_MODE:
                run_mapping_mode(page)
                return 0

            output_path = run_download_mode(page)
            print()
            print("Download completed successfully:")
            print(output_path)
            return 0

        except Exception as error:
            print()
            print(f"Automation failed: {error}")
            print("The browser will stay open so you can inspect the page.")
            input("Press Enter to close the browser... ")
            return 1

        finally:
            browser.close()


if __name__ == "__main__":
    raise SystemExit(main())
